// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/punchin.proto

package com.smartphonedev.protobuf;

/**
 * Protobuf type {@code com.smartphonedev.protobuf.PunchIn}
 */
public final class PunchIn extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.smartphonedev.protobuf.PunchIn)
    PunchInOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PunchIn.newBuilder() to construct.
  private PunchIn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PunchIn() {
    firstName_ = "";
    lastName_ = "";
    staffID_ = "";
    utcTimestamp_ = "";
    storeID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PunchIn();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PunchIn(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            firstName_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            lastName_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            staffID_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            utcTimestamp_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            storeID_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartphonedev.protobuf.PunchInProtobuf.internal_static_com_smartphonedev_protobuf_PunchIn_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartphonedev.protobuf.PunchInProtobuf.internal_static_com_smartphonedev_protobuf_PunchIn_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartphonedev.protobuf.PunchIn.class, com.smartphonedev.protobuf.PunchIn.Builder.class);
  }

  private int bitField0_;
  public static final int FIRSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object firstName_;
  /**
   * <code>optional string firstName = 1;</code>
   * @return Whether the firstName field is set.
   */
  @java.lang.Override
  public boolean hasFirstName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string firstName = 1;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        firstName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object lastName_;
  /**
   * <code>optional string LastName = 2;</code>
   * @return Whether the lastName field is set.
   */
  @java.lang.Override
  public boolean hasLastName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string LastName = 2;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        lastName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string LastName = 2;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAFFID_FIELD_NUMBER = 3;
  private volatile java.lang.Object staffID_;
  /**
   * <code>optional string staffID = 3;</code>
   * @return Whether the staffID field is set.
   */
  @java.lang.Override
  public boolean hasStaffID() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string staffID = 3;</code>
   * @return The staffID.
   */
  @java.lang.Override
  public java.lang.String getStaffID() {
    java.lang.Object ref = staffID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        staffID_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string staffID = 3;</code>
   * @return The bytes for staffID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStaffIDBytes() {
    java.lang.Object ref = staffID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      staffID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UTCTIMESTAMP_FIELD_NUMBER = 4;
  private volatile java.lang.Object utcTimestamp_;
  /**
   * <code>optional string utcTimestamp = 4;</code>
   * @return Whether the utcTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasUtcTimestamp() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string utcTimestamp = 4;</code>
   * @return The utcTimestamp.
   */
  @java.lang.Override
  public java.lang.String getUtcTimestamp() {
    java.lang.Object ref = utcTimestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        utcTimestamp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string utcTimestamp = 4;</code>
   * @return The bytes for utcTimestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUtcTimestampBytes() {
    java.lang.Object ref = utcTimestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      utcTimestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STOREID_FIELD_NUMBER = 5;
  private volatile java.lang.Object storeID_;
  /**
   * <code>optional string storeID = 5;</code>
   * @return Whether the storeID field is set.
   */
  @java.lang.Override
  public boolean hasStoreID() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string storeID = 5;</code>
   * @return The storeID.
   */
  @java.lang.Override
  public java.lang.String getStoreID() {
    java.lang.Object ref = storeID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        storeID_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string storeID = 5;</code>
   * @return The bytes for storeID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStoreIDBytes() {
    java.lang.Object ref = storeID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      storeID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, staffID_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, utcTimestamp_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, storeID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, staffID_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, utcTimestamp_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, storeID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartphonedev.protobuf.PunchIn)) {
      return super.equals(obj);
    }
    com.smartphonedev.protobuf.PunchIn other = (com.smartphonedev.protobuf.PunchIn) obj;

    if (hasFirstName() != other.hasFirstName()) return false;
    if (hasFirstName()) {
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
    }
    if (hasLastName() != other.hasLastName()) return false;
    if (hasLastName()) {
      if (!getLastName()
          .equals(other.getLastName())) return false;
    }
    if (hasStaffID() != other.hasStaffID()) return false;
    if (hasStaffID()) {
      if (!getStaffID()
          .equals(other.getStaffID())) return false;
    }
    if (hasUtcTimestamp() != other.hasUtcTimestamp()) return false;
    if (hasUtcTimestamp()) {
      if (!getUtcTimestamp()
          .equals(other.getUtcTimestamp())) return false;
    }
    if (hasStoreID() != other.hasStoreID()) return false;
    if (hasStoreID()) {
      if (!getStoreID()
          .equals(other.getStoreID())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFirstName()) {
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
    }
    if (hasLastName()) {
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
    }
    if (hasStaffID()) {
      hash = (37 * hash) + STAFFID_FIELD_NUMBER;
      hash = (53 * hash) + getStaffID().hashCode();
    }
    if (hasUtcTimestamp()) {
      hash = (37 * hash) + UTCTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getUtcTimestamp().hashCode();
    }
    if (hasStoreID()) {
      hash = (37 * hash) + STOREID_FIELD_NUMBER;
      hash = (53 * hash) + getStoreID().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartphonedev.protobuf.PunchIn parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartphonedev.protobuf.PunchIn parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartphonedev.protobuf.PunchIn parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartphonedev.protobuf.PunchIn parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartphonedev.protobuf.PunchIn prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.smartphonedev.protobuf.PunchIn}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.smartphonedev.protobuf.PunchIn)
      com.smartphonedev.protobuf.PunchInOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartphonedev.protobuf.PunchInProtobuf.internal_static_com_smartphonedev_protobuf_PunchIn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartphonedev.protobuf.PunchInProtobuf.internal_static_com_smartphonedev_protobuf_PunchIn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartphonedev.protobuf.PunchIn.class, com.smartphonedev.protobuf.PunchIn.Builder.class);
    }

    // Construct using com.smartphonedev.protobuf.PunchIn.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      firstName_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      lastName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      staffID_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      utcTimestamp_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      storeID_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartphonedev.protobuf.PunchInProtobuf.internal_static_com_smartphonedev_protobuf_PunchIn_descriptor;
    }

    @java.lang.Override
    public com.smartphonedev.protobuf.PunchIn getDefaultInstanceForType() {
      return com.smartphonedev.protobuf.PunchIn.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartphonedev.protobuf.PunchIn build() {
      com.smartphonedev.protobuf.PunchIn result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartphonedev.protobuf.PunchIn buildPartial() {
      com.smartphonedev.protobuf.PunchIn result = new com.smartphonedev.protobuf.PunchIn(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.firstName_ = firstName_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.lastName_ = lastName_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.staffID_ = staffID_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.utcTimestamp_ = utcTimestamp_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.storeID_ = storeID_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartphonedev.protobuf.PunchIn) {
        return mergeFrom((com.smartphonedev.protobuf.PunchIn)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartphonedev.protobuf.PunchIn other) {
      if (other == com.smartphonedev.protobuf.PunchIn.getDefaultInstance()) return this;
      if (other.hasFirstName()) {
        bitField0_ |= 0x00000001;
        firstName_ = other.firstName_;
        onChanged();
      }
      if (other.hasLastName()) {
        bitField0_ |= 0x00000002;
        lastName_ = other.lastName_;
        onChanged();
      }
      if (other.hasStaffID()) {
        bitField0_ |= 0x00000004;
        staffID_ = other.staffID_;
        onChanged();
      }
      if (other.hasUtcTimestamp()) {
        bitField0_ |= 0x00000008;
        utcTimestamp_ = other.utcTimestamp_;
        onChanged();
      }
      if (other.hasStoreID()) {
        bitField0_ |= 0x00000010;
        storeID_ = other.storeID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartphonedev.protobuf.PunchIn parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartphonedev.protobuf.PunchIn) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object firstName_ = "";
    /**
     * <code>optional string firstName = 1;</code>
     * @return Whether the firstName field is set.
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string firstName = 1;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string firstName = 1;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string firstName = 1;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string firstName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string firstName = 1;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>optional string LastName = 2;</code>
     * @return Whether the lastName field is set.
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string LastName = 2;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string LastName = 2;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string LastName = 2;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string LastName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string LastName = 2;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      lastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object staffID_ = "";
    /**
     * <code>optional string staffID = 3;</code>
     * @return Whether the staffID field is set.
     */
    public boolean hasStaffID() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string staffID = 3;</code>
     * @return The staffID.
     */
    public java.lang.String getStaffID() {
      java.lang.Object ref = staffID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          staffID_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string staffID = 3;</code>
     * @return The bytes for staffID.
     */
    public com.google.protobuf.ByteString
        getStaffIDBytes() {
      java.lang.Object ref = staffID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staffID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string staffID = 3;</code>
     * @param value The staffID to set.
     * @return This builder for chaining.
     */
    public Builder setStaffID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      staffID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string staffID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStaffID() {
      bitField0_ = (bitField0_ & ~0x00000004);
      staffID_ = getDefaultInstance().getStaffID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string staffID = 3;</code>
     * @param value The bytes for staffID to set.
     * @return This builder for chaining.
     */
    public Builder setStaffIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      staffID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object utcTimestamp_ = "";
    /**
     * <code>optional string utcTimestamp = 4;</code>
     * @return Whether the utcTimestamp field is set.
     */
    public boolean hasUtcTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string utcTimestamp = 4;</code>
     * @return The utcTimestamp.
     */
    public java.lang.String getUtcTimestamp() {
      java.lang.Object ref = utcTimestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          utcTimestamp_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string utcTimestamp = 4;</code>
     * @return The bytes for utcTimestamp.
     */
    public com.google.protobuf.ByteString
        getUtcTimestampBytes() {
      java.lang.Object ref = utcTimestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        utcTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string utcTimestamp = 4;</code>
     * @param value The utcTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setUtcTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      utcTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string utcTimestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtcTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      utcTimestamp_ = getDefaultInstance().getUtcTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string utcTimestamp = 4;</code>
     * @param value The bytes for utcTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setUtcTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      utcTimestamp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object storeID_ = "";
    /**
     * <code>optional string storeID = 5;</code>
     * @return Whether the storeID field is set.
     */
    public boolean hasStoreID() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string storeID = 5;</code>
     * @return The storeID.
     */
    public java.lang.String getStoreID() {
      java.lang.Object ref = storeID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          storeID_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string storeID = 5;</code>
     * @return The bytes for storeID.
     */
    public com.google.protobuf.ByteString
        getStoreIDBytes() {
      java.lang.Object ref = storeID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string storeID = 5;</code>
     * @param value The storeID to set.
     * @return This builder for chaining.
     */
    public Builder setStoreID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      storeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string storeID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreID() {
      bitField0_ = (bitField0_ & ~0x00000010);
      storeID_ = getDefaultInstance().getStoreID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string storeID = 5;</code>
     * @param value The bytes for storeID to set.
     * @return This builder for chaining.
     */
    public Builder setStoreIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      storeID_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.smartphonedev.protobuf.PunchIn)
  }

  // @@protoc_insertion_point(class_scope:com.smartphonedev.protobuf.PunchIn)
  private static final com.smartphonedev.protobuf.PunchIn DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartphonedev.protobuf.PunchIn();
  }

  public static com.smartphonedev.protobuf.PunchIn getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PunchIn>
      PARSER = new com.google.protobuf.AbstractParser<PunchIn>() {
    @java.lang.Override
    public PunchIn parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PunchIn(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PunchIn> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PunchIn> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartphonedev.protobuf.PunchIn getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

