// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/punchin.proto

package com.smartphonedev.protobuf;

public final class PunchInProtobuf {
  private PunchInProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartphonedev_protobuf_PunchIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartphonedev_protobuf_PunchIn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protocol/punchin.proto\022\032com.smartphone" +
      "dev.protobuf\"f\n\007PunchIn\022\021\n\tfirstName\030\001 \001" +
      "(\t\022\020\n\010LastName\030\002 \001(\t\022\017\n\007staffID\030\003 \001(\t\022\024\n" +
      "\014utcTimestamp\030\004 \001(\t\022\017\n\007storeID\030\005 \001(\tB/\n\032" +
      "com.smartphonedev.protobufB\017PunchInProto" +
      "bufP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_smartphonedev_protobuf_PunchIn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smartphonedev_protobuf_PunchIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartphonedev_protobuf_PunchIn_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "StaffID", "UtcTimestamp", "StoreID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
