// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/punchin.proto

package com.smartphonedev.protobuf;

public interface PunchInOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smartphonedev.protobuf.PunchIn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string firstName = 1;</code>
   * @return Whether the firstName field is set.
   */
  boolean hasFirstName();
  /**
   * <code>optional string firstName = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string LastName = 2;</code>
   * @return Whether the lastName field is set.
   */
  boolean hasLastName();
  /**
   * <code>optional string LastName = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>optional string LastName = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>optional string staffID = 3;</code>
   * @return Whether the staffID field is set.
   */
  boolean hasStaffID();
  /**
   * <code>optional string staffID = 3;</code>
   * @return The staffID.
   */
  java.lang.String getStaffID();
  /**
   * <code>optional string staffID = 3;</code>
   * @return The bytes for staffID.
   */
  com.google.protobuf.ByteString
      getStaffIDBytes();

  /**
   * <code>optional string utcTimestamp = 4;</code>
   * @return Whether the utcTimestamp field is set.
   */
  boolean hasUtcTimestamp();
  /**
   * <code>optional string utcTimestamp = 4;</code>
   * @return The utcTimestamp.
   */
  java.lang.String getUtcTimestamp();
  /**
   * <code>optional string utcTimestamp = 4;</code>
   * @return The bytes for utcTimestamp.
   */
  com.google.protobuf.ByteString
      getUtcTimestampBytes();

  /**
   * <code>optional string storeID = 5;</code>
   * @return Whether the storeID field is set.
   */
  boolean hasStoreID();
  /**
   * <code>optional string storeID = 5;</code>
   * @return The storeID.
   */
  java.lang.String getStoreID();
  /**
   * <code>optional string storeID = 5;</code>
   * @return The bytes for storeID.
   */
  com.google.protobuf.ByteString
      getStoreIDBytes();
}
